function tracks(){return read(TRACK_KEY,seedTracks)}
function trainings(){return read(TRAINING_KEY,seedTrainings)}
function saveTracks(x){localStorage.setItem(TRACK_KEY,JSON.stringify(x))}
function saveTrainings(x){localStorage.setItem(TRAINING_KEY,JSON.stringify(x))}
function showSection(section){document.querySelectorAll('.admin-section').forEach(x=>x.classList.toggle('active',x.id==='section-'+section));document.querySelectorAll('.side-link').forEach(x=>x.classList.toggle('active',x.dataset.section===section));if(section==='tracks')renderTracks();if(section==='trainings')renderTrainings();if(section==='materials')renderMaterials()}
function refreshOverview(){const tr=tracks(),tn=trainings();statTracks.textContent=tr.length;statTrainings.textContent=tn.length;statPublished.textContent=tn.filter(x=>x.published).length;statDrafts.textContent=tn.filter(x=>!x.published).length;overviewTracks.innerHTML=tr.slice(0,4).map(x=>miniRow(x.title,x.published?'PUBLICADA':'RASCUNHO',x.trainingIds.length+' treinamentos')).join('')||'<div class="empty-state small">Nenhuma trilha cadastrada.</div>';overviewTrainings.innerHTML=tn.slice(0,4).map(x=>miniRow(x.title,x.published?'PUBLICADO':'RASCUNHO',(x.contents||[]).length+' conteúdos')).join('')||'<div class="empty-state small">Nenhum treinamento cadastrado.</div>'}
function miniRow(title,status,meta){return `<div class="mini-row"><div><strong>${esc(title)}</strong><span>${esc(meta)}</span></div><span class="status ${status.includes('PUBLIC')?'published':'draft'}">${status}</span></div>`}
function renderTracks(){const all=tracks(),q=(trackSearch?.value||'').toLowerCase(),f=trackFilter?.value||'all';const data=all.filter(x=>(x.title+x.description).toLowerCase().includes(q)).filter(x=>f==='all'||(f==='published'?x.published:!x.published));trackList.innerHTML=data.length?data.map(t=>{const count=t.trainingIds.length;return `<article class="admin-row"><div class="row-avatar">◈</div><div class="row-content"><h3>${esc(t.title)}</h3><p>${esc(t.description||'Sem descrição cadastrada.')}</p><div class="training-tags"><span class="tag">${esc(t.level)}</span><span class="tag">${t.hours}h</span><span class="tag">${count} treinamentos</span><span class="status ${t.published?'published':'draft'}">${t.published?'PUBLICADA':'RASCUNHO'}</span></div></div><div class="row-actions"><button class="icon-btn" onclick="openTrackEditor('${t.id}')">Editar</button><button class="icon-btn" onclick="toggleTrack('${t.id}')">${t.published?'Despublicar':'Publicar'}</button><button class="icon-btn" style="color:#dc2626" onclick="deleteTrack('${t.id}')">Excluir</button></div></article>`}).join(''):'<div class="empty-state">Nenhuma trilha encontrada.</div>'}
function renderTrainings(){const all=trainings(),q=(trainingSearch?.value||'').toLowerCase(),f=trainingFilter?.value||'all';const data=all.filter(x=>(x.title+x.description).toLowerCase().includes(q)).filter(x=>f==='all'||(f==='published'?x.published:!x.published));trainingList.innerHTML=data.length?data.map(t=>{const track=tracks().find(x=>x.id===t.trackId);return `<article class="admin-row"><div class="row-avatar">⌘</div><div class="row-content"><h3>${esc(t.title)}</h3><p>${esc(t.description||'Sem descrição cadastrada.')}</p><div class="training-tags"><span class="tag">${esc(track?.title||'Sem trilha')}</span><span class="tag">${(t.contents||[]).length} conteúdos</span><span class="status ${t.published?'published':'draft'}">${t.published?'PUBLICADO':'RASCUNHO'}</span></div></div><div class="row-actions"><button class="icon-btn" onclick="openTrainingEditor('${t.id}')">Editar</button><button class="icon-btn" onclick="toggleTraining('${t.id}')">${t.published?'Despublicar':'Publicar'}</button><button class="icon-btn" style="color:#dc2626" onclick="deleteTraining('${t.id}')">Excluir</button></div></article>`}).join(''):'<div class="empty-state">Nenhum treinamento encontrado.</div>'}
function renderMaterials(){const list=[];trainings().forEach(t=>(t.contents||[]).forEach(c=>list.push({...c,training:t.title})));materialList.innerHTML=list.length?list.map(c=>`<article class="material-card"><div class="material-icon">${c.type==='Vídeo'?'▶':c.type==='PDF'?'PDF':'▤'}</div><div><span class="tag">${esc(c.type)}</span><h3>${esc(c.title)}</h3><p>${esc(c.training)}</p>${c.url?`<a href="${esc(c.url)}" target="_blank" rel="noopener">Abrir recurso ↗</a>`:'<small>Recurso ainda não informado</small>'}</div></article>`).join(''):'<div class="empty-state">Nenhum conteúdo cadastrado.</div>'}
function openTrackEditor(id=''){const t=id?tracks().find(x=>x.id===id):{id:'',title:'',description:'',level:'Iniciante',hours:10,image:'',published:false,trainingIds:[]};trackEditorTitle.textContent=id?'Editar trilha':'Nova trilha';trackId.value=t.id;trackTitle.value=t.title;trackDescription.value=t.description;trackLevel.value=t.level;trackHours.value=t.hours;trackImage.value=t.image||'';trackPublished.checked=!!t.published;renderTrackTrainingOrder(t.trainingIds||[]);updateTrackPublishText();trackOverlay.classList.add('open')}
function closeTrackEditor(){trackOverlay.classList.remove('open')}
function getEditorTrackIds(){return [...document.querySelectorAll('#trackTrainingOrder .order-row')].map(row=>row.dataset.id).filter(Boolean)}
// Mantém a ordem em memória enquanto o editor está aberto.
let editorTrackIds=[];
function renderTrackTrainingOrder(ids){editorTrackIds=[...ids];const all=trainings();trackTrainingOrder.innerHTML=editorTrackIds.length?editorTrackIds.map((id,i)=>{const t=all.find(x=>x.id===id);if(!t)return '';return `<div class="order-row" data-id="${id}"><span class="order-number">${i+1}</span><div><strong>${esc(t.title)}</strong><small>${t.published?'Publicado':'Rascunho'}</small></div><div class="order-actions"><button type="button" onclick="moveTrackTraining(${i},-1)">↑</button><button type="button" onclick="moveTrackTraining(${i},1)">↓</button><button type="button" onclick="removeFromTrack(${i})">×</button></div></div>`}).join(''):'<div class="empty-state small">Nenhum treinamento associado ainda.</div>'}
function moveTrackTraining(i,d){const n=i+d;if(n<0||n>=editorTrackIds.length)return;[editorTrackIds[i],editorTrackIds[n]]=[editorTrackIds[n],editorTrackIds[i]];renderTrackTrainingOrder(editorTrackIds)}
function removeFromTrack(i){editorTrackIds.splice(i,1);renderTrackTrainingOrder(editorTrackIds)}
function updateTrackPublishText(){trackPublishText.textContent=trackPublished.checked?'A trilha será publicada e ficará disponível para os alunos.':'Esta trilha ficará salva como rascunho e não aparecerá para os alunos.'}
function toggleTrack(id){const d=tracks(),t=d.find(x=>x.id===id);if(t){t.published=!t.published;saveTracks(d);renderTracks();refreshOverview()}}
function refreshAll(){renderTracks();renderTrainings();renderMaterials();refreshOverview()}
function deleteTrack(id){const t=tracks().find(x=>x.id===id);if(!t)return;
const n=trainings().filter(x=>x.trackId===id||(t.trainingIds||[]).includes(x.id)).length;
if(!confirm(`Excluir a trilha "${t.title}"?`+(n?`\n\nOs ${n} treinamento(s) vinculados NÃO serão excluídos; ficarão sem trilha.`:'')+'\n\nEsta ação não pode ser desfeita.'))return;
saveTracks(tracks().filter(x=>x.id!==id));
const tn=trainings();tn.forEach(x=>{if(x.trackId===id)x.trackId=''});saveTrainings(tn);refreshAll()}
function deleteTraining(id){const t=trainings().find(x=>x.id===id);if(!t)return;
if(!confirm(`Excluir o treinamento "${t.title}"?\n\nSeus ${(t.contents||[]).length} conteúdo(s) e ${(t.quiz||[]).length} pergunta(s) do quiz também serão removidos. Esta ação não pode ser desfeita.`))return;
saveTrainings(trainings().filter(x=>x.id!==id));
const d=tracks();d.forEach(x=>{x.trainingIds=(x.trainingIds||[]).filter(i=>i!==id)});saveTracks(d);refreshAll()}
function openTrainingEditor(id='',trackId=''){const t=id?trainings().find(x=>x.id===id):{id:'',title:'',description:'',level:'Iniciante',hours:1,image:'',trackId:trackId||tracks()[0]?.id||'',published:false,contents:[],files:[]};trainingEditorTitle.textContent=id?'Editar treinamento':'Novo treinamento';trainingId.value=t.id;trainingTitle.value=t.title;trainingDescription.value=t.description;trainingLevel.value=t.level;trainingHours.value=t.hours;trainingImage.value=t.image||'';trainingPublished.checked=!!t.published;populateTrackSelect(t.trackId);window.editorContents=JSON.parse(JSON.stringify(t.contents||[]));window.editorFiles=[...(t.files||[])];window.editorQuiz=JSON.parse(JSON.stringify(t.quiz||[]));renderTrainingContents();renderQuizEditor();renderTrainingFiles();updateTrainingPublishText();trainingOverlay.classList.add('open')}
function closeTrainingEditor(){trainingOverlay.classList.remove('open')}
function populateTrackSelect(selected){trainingTrack.innerHTML=tracks().map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${esc(t.title)}</option>`).join('');if(!trainingTrack.options.length)trainingTrack.innerHTML='<option value="">Sem trilha</option>'}
function addTrainingContent(){editorContents.push({id:'c'+Date.now()+Math.random().toString(16).slice(2),type:'Vídeo',title:'Novo conteúdo',url:'',duration:''});renderTrainingContents();renderQuizEditor()}
function renderTrainingContents(){trainingContentEditor.innerHTML=editorContents.length?editorContents.map((c,i)=>`<div class="content-editor"><div class="content-index">${i+1}</div><div class="content-fields"><div class="form-grid"><select onchange="editorContents[${i}].type=this.value"><option ${c.type==='Vídeo'?'selected':''}>Vídeo</option><option ${c.type==='PDF'?'selected':''}>PDF</option><option ${c.type==='Material'?'selected':''}>Material</option></select><input value="${esc(c.title)}" placeholder="Título" onchange="editorContents[${i}].title=this.value"></div><div class="form-grid"><input value="${esc(c.url)}" placeholder="URL do vídeo, PDF ou material" onchange="editorContents[${i}].url=this.value"><input value="${esc(c.duration)}" placeholder="Duração / páginas" onchange="editorContents[${i}].duration=this.value"></div></div><button type="button" class="icon-btn danger" onclick="removeTrainingContent(${i})">×</button></div>`).join(''):'<div class="empty-state small">Nenhum conteúdo. Clique em “Adicionar conteúdo”.</div>'}
function removeTrainingContent(i){const id=editorContents[i].id;editorContents.splice(i,1);editorQuiz.forEach(q=>{if(q.src===id)q.src=''});renderTrainingContents();renderQuizEditor()}
function addQuizQuestion(){editorQuiz.push({q:'',o:['','','',''],src:''});renderQuizEditor()}
function removeQuizQuestion(i){editorQuiz.splice(i,1);renderQuizEditor()}
function renderQuizEditor(){trainingQuizEditor.innerHTML=editorQuiz.length?editorQuiz.map((q,i)=>`<div class="content-editor"><div class="content-index">${i+1}</div><div class="content-fields"><input value="${esc(q.q)}" placeholder="Pergunta" onchange="editorQuiz[${i}].q=this.value"><select onchange="editorQuiz[${i}].src=this.value"><option value="">Baseada em: material geral</option>${editorContents.map(c=>`<option value="${esc(c.id)}" ${c.id===q.src?'selected':''}>${esc(c.type)} — ${esc(c.title)}</option>`).join('')}</select>${q.o.map((o,j)=>`<input value="${esc(o)}" placeholder="${j?'Alternativa incorreta':'Resposta correta'}" onchange="editorQuiz[${i}].o[${j}]=this.value">`).join('')}</div><button type="button" class="icon-btn danger" onclick="removeQuizQuestion(${i})">×</button></div>`).join(''):'<div class="empty-state small">Nenhuma pergunta. Clique em “Adicionar pergunta”.</div>'}
function renderTrainingFiles(){trainingFileList.innerHTML=editorFiles.map(f=>`<div class="file-item">📎 ${esc(f)}</div>`).join('')}
function updateTrainingPublishText(){trainingPublishText.textContent=trainingPublished.checked?'O treinamento será publicado e ficará disponível na trilha selecionada.':'Este treinamento ficará salvo como rascunho.'}
function toggleTraining(id){const d=trainings(),t=d.find(x=>x.id===id);if(t){t.published=!t.published;saveTrainings(d);renderTrainings();refreshOverview()}}

document.addEventListener('DOMContentLoaded',()=>{
  if(!document.body.classList.contains('admin-shell'))return;
  const s=getAdminSession();adminName.textContent=s?.name||'Administrador';adminRole.textContent=s?.role||'Administrador';welcomeAdmin.textContent=(s?.name||'Administrador').split(' ')[0];
  read(TRACK_KEY,seedTracks);read(TRAINING_KEY,seedTrainings);refreshOverview();renderTracks();renderTrainings();renderMaterials();
  document.querySelectorAll('.side-link').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
  trackForm.addEventListener('submit',e=>{e.preventDefault();const d=tracks();const item={id:trackId.value||'tr'+Date.now(),title:trackTitle.value.trim(),description:trackDescription.value.trim(),level:trackLevel.value,hours:Number(trackHours.value||0),image:trackImage.value.trim(),published:trackPublished.checked,trainingIds:[...editorTrackIds],quiz:(tracks().find(x=>x.id===trackId.value)||{}).quiz||[]};const i=d.findIndex(x=>x.id===item.id);if(i>=0)d[i]=item;else d.push(item);saveTracks(d);{const tn=trainings();tn.forEach(x=>{if(item.trainingIds.includes(x.id))x.trackId=item.id;else if(x.trackId===item.id)x.trackId=''});saveTrainings(tn)}closeTrackEditor();refreshOverview();renderTracks();renderTrainings();populateTrackSelect(item.id)});
  trainingForm.addEventListener('submit',e=>{e.preventDefault();const d=trainings();const quiz=editorQuiz.filter(q=>q.q.trim()&&q.o.every(o=>o.trim())).map(q=>({...q,q:q.q.trim(),o:q.o.map(o=>o.trim())}));if(quiz.length<editorQuiz.length)alert('Perguntas incompletas (sem enunciado ou alternativas) foram descartadas.');const item={id:trainingId.value||'t'+Date.now(),title:trainingTitle.value.trim(),description:trainingDescription.value.trim(),level:trainingLevel.value,hours:Number(trainingHours.value||0),image:trainingImage.value.trim(),trackId:trainingTrack.value,published:trainingPublished.checked,contents:editorContents.map(c=>({...c,url:safeUrl(c.url)})),quiz,files:[...editorFiles,...[...(trainingFiles.files||[])].map(f=>f.name)]};const i=d.findIndex(x=>x.id===item.id);if(i>=0)d[i]=item;else d.push(item);saveTrainings(d);const tr=tracks();tr.forEach(t=>{if(t.id!==item.trackId)t.trainingIds=t.trainingIds.filter(x=>x!==item.id)});const target=tr.find(t=>t.id===item.trackId);if(target&&!target.trainingIds.includes(item.id))target.trainingIds.push(item.id);saveTracks(tr);closeTrainingEditor();refreshOverview();renderTracks();renderTrainings();renderMaterials()});
  trainingFiles.addEventListener('change',()=>{editorFiles=[...editorFiles,...[...trainingFiles.files].map(f=>f.name)];renderTrainingFiles()});
});
