const STORAGE_KEY="formatiState";
const defaultState={userName:"Andressa",progress:0,completedLessons:[],quizScore:null,certificate:false};
function getState(){return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}
function saveState(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function logout(){localStorage.removeItem(STORAGE_KEY);location.href="index.html"}
function updateProgress(){const s=getState();const total=6;const progress=Math.round((s.completedLessons.length/total)*100);s.progress=Math.min(progress,100);saveState(s);return s.progress}
function initLogin(){const f=document.getElementById("loginForm");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();const s=getState();const email=document.getElementById("email").value;s.userName=email.split("@")[0]||"Aluno";saveState(s);location.href="dashboard.html"})}
function initDashboard(){const s=getState(),p=updateProgress();const n=document.getElementById("userName");if(n)n.textContent=s.userName.charAt(0).toUpperCase()+s.userName.slice(1);document.getElementById("statProgress")&&(document.getElementById("statProgress").textContent=p+"%");document.getElementById("dashboardProgress")&&(document.getElementById("dashboardProgress").textContent=p+"%");document.getElementById("dashboardBar")&&(document.getElementById("dashboardBar").style.width=p+"%");document.getElementById("statCompleted")&&(document.getElementById("statCompleted").textContent=s.certificate?1:0);document.getElementById("statCertificates")&&(document.getElementById("statCertificates").textContent=s.certificate?1:0)}
const lessons=[
 {id:"l1",module:"Módulo 1 — Fundamentos",type:"VÍDEO",title:"O que é tecnologia?",time:"12 min",text:"Conheça os conceitos fundamentais de tecnologia e sistemas digitais."},
 {id:"l2",module:"Módulo 1 — Fundamentos",type:"PDF",title:"Guia de fundamentos digitais",time:"PDF • 8 páginas",text:"Material de apoio com os principais conceitos estudados."},
 {id:"l3",module:"Módulo 2 — Internet",type:"VÍDEO",title:"Como funciona a Internet",time:"18 min",text:"Entenda dispositivos, redes, servidores e comunicação."},
 {id:"l4",module:"Módulo 2 — Internet",type:"PDF",title:"Internet e redes",time:"PDF • 12 páginas",text:"Resumo sobre redes, endereçamento e comunicação."},
 {id:"l5",module:"Módulo 3 — Segurança",type:"VÍDEO",title:"Segurança digital na prática",time:"15 min",text:"Aprenda práticas essenciais para proteger contas e dados."},
 {id:"l6",module:"Módulo 3 — Segurança",type:"PDF",title:"Checklist de segurança",time:"PDF • 6 páginas",text:"Checklist para aplicar boas práticas de segurança digital."}
];
function initLibrary(){const box=document.getElementById("modules");if(!box)return;const s=getState();const groups={};lessons.forEach(l=>(groups[l.module]??=[]).push(l));box.innerHTML=Object.entries(groups).map(([name,items])=>`<article class="module"><div class="module-head"><h3>${name}</h3><span>${items.filter(x=>s.completedLessons.includes(x.id)).length}/${items.length}</span></div><div class="lessons">${items.map(l=>`<div class="lesson ${s.completedLessons.includes(l.id)?"done":""}"><div class="lesson-type">${l.type==="PDF"?"PDF":"▶"}</div><div class="lesson-info"><strong>${l.title}</strong><span>${l.time}</span></div><a class="btn secondary" href="estudo.html?id=${l.id}">Estudar</a><button class="check" onclick="toggleLesson('${l.id}')">${s.completedLessons.includes(l.id)?"✓":""}</button></div>`).join("")}</div></article>`).join("");const p=updateProgress();document.getElementById("libraryPercent").textContent=p+"%";document.getElementById("libraryBar").style.width=p+"%";document.getElementById("quizCta").style.opacity=p===100?1:.55}
function toggleLesson(id){const s=getState();s.completedLessons=s.completedLessons.includes(id)?s.completedLessons.filter(x=>x!==id):[...s.completedLessons,id];saveState(s);initLibrary()}
function initStudy(){const box=document.getElementById("studyContent");if(!box)return;const id=new URLSearchParams(location.search).get("id")||"l1";const l=lessons.find(x=>x.id===id)||lessons[0];const s=getState();const done=s.completedLessons.includes(l.id);box.innerHTML=`<div class="study-card"><span class="tag">${l.type}</span><h1>${l.title}</h1><p class="muted">${l.text}</p>${l.type==="VÍDEO"?'<div class="video-placeholder">▶</div>':'<div class="pdf-placeholder">Visualização do PDF</div>'}<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:22px"><span class="muted">${l.time}</span><button class="btn primary" onclick="toggleLesson('${l.id}'); location.href='biblioteca.html'">${done?"Concluído ✓":"Marcar como concluído"}</button></div></div>`}
const questions=[
["Qual componente é responsável por executar instruções em um computador?","CPU","Monitor","Teclado","Roteador"],
["Qual protocolo é utilizado para acessar páginas web com segurança?","HTTPS","FTP","SMTP","DHCP"],
["Qual prática ajuda a proteger uma conta online?","Usar autenticação em dois fatores","Repetir a mesma senha","Compartilhar a senha","Desativar atualizações"],
["O que representa um endereço IP?","Um identificador de um dispositivo em uma rede","Um tipo de monitor","Um formato de arquivo","Uma linguagem de programação"],
["Qual atitude reduz riscos de phishing?","Verificar o remetente e o endereço do link","Clicar em qualquer promoção","Informar senha por mensagem","Desativar o antivírus"]
];
function initQuiz(){const form=document.getElementById("quizForm");if(!form)return;let current=0;form.innerHTML=questions.map((q,i)=>`<div class="question ${i===0?"active":""}" data-q="${i}"><p class="eyebrow">QUESTÃO ${i+1} DE ${questions.length}</p><h2>${q[0]}</h2><div class="options">${q.slice(1).map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required> <span>${o}</span></label>`).join("")}</div><div class="quiz-nav">${i?'<button type="button" class="btn secondary prev">Anterior</button>':'<span></span>'}${i<questions.length-1?'<button type="button" class="btn primary next">Próxima</button>':'<button type="submit" class="btn primary">Finalizar quiz</button>'}</div></div>`).join("");const qs=[...form.querySelectorAll(".question")];function show(n){qs.forEach((q,i)=>q.classList.toggle("active",i===n));document.getElementById("questionCount").textContent=`Questão ${n+1} de ${questions.length}`;document.getElementById("quizBar").style.width=((n+1)/questions.length*100)+"%"}form.addEventListener("click",e=>{if(e.target.classList.contains("next")){if(!qs[current].querySelector("input:checked"))return alert("Selecione uma resposta.");current++;show(current)}if(e.target.classList.contains("prev")){current--;show(current)}});form.addEventListener("submit",e=>{e.preventDefault();if(!qs[current].querySelector("input:checked"))return alert("Selecione uma resposta.");let score=0;questions.forEach((q,i)=>{const a=form.querySelector(`input[name="q${i}"]:checked`);if(a&&Number(a.value)===[0,0,0,0,0][i])score++});const percent=Math.round(score/questions.length*100);const s=getState();s.quizScore=percent;s.certificate=percent>=70;saveState(s);location.href="resultado.html"});show(0)}
function initResult(){const s=getState(),score=s.quizScore??0;document.getElementById("scoreValue").textContent=score+"%";const ok=score>=70;document.getElementById("resultTitle").textContent=ok?"Parabéns!":"Quase lá!";document.getElementById("resultText").textContent=ok?"Você foi aprovado e já pode emitir seu certificado de conclusão.":"Você precisa de pelo menos 70% para concluir a trilha. Revise os materiais e tente novamente.";document.getElementById("resultIcon").textContent=ok?"✓":"!";document.getElementById("resultAction").textContent=ok?"Emitir certificado":"Refazer quiz";document.getElementById("resultAction").href=ok?"certificado.html":"quiz.html"}
function initCertificate(){const s=getState();document.getElementById("certificateName").textContent=s.userName.charAt(0).toUpperCase()+s.userName.slice(1);document.getElementById("certificateDate").textContent=new Date().toLocaleDateString("pt-BR");if(!s.certificate)document.querySelector(".certificate-actions").innerHTML='<a class="btn primary" href="quiz.html">Concluir avaliação primeiro</a>'}
document.addEventListener("DOMContentLoaded",()=>{initLogin();initDashboard();initLibrary();initStudy();initQuiz();initResult();if(document.getElementById("certificate"))initCertificate()});
